# Generated by Django 3.1.5 on 2021-02-15 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category_out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('money_cd', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='日付')),
                ('detail', models.CharField(max_length=200, verbose_name='概要')),
                ('cost', models.IntegerField(default=0, verbose_name='金額')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='money.category_in')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expence',
            fields=[
                ('money_cd', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='日付')),
                ('detail', models.CharField(max_length=200, verbose_name='概要')),
                ('cost', models.IntegerField(default=0, verbose_name='金額')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='money.category_out')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
