# Generated by Django 3.1.5 on 2021-02-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expence',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(verbose_name='日付'),
        ),
    ]
